:bug: QD-11464: Perform an explicit build in CI to avoid panics on test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,11 +50,17 @@ jobs:
           registry: registry.jetbrains.team
           username: ${{ secrets.SPACE_USERNAME }}
           password: ${{ secrets.SPACE_PASSWORD }}
+      - name: Build
+        # Build everything that will be tested. Although go test performs a build itself, gotestfmt will panic on a
+        # failed build.
+        run: |
+          set -euo pipefail
+          go build -v $(go list -m)
       - name: Run tests (with coverage)
         if: ${{ matrix.os != 'windows-latest' }}
         run: |
           set -euo pipefail
-          go test -json -v $(go list -f '{{.Dir}}/...' -m | xargs) -coverprofile coverage-${{ matrix.os }}.out 2>&1 | tee /tmp/gotest.log | gotestfmt
+          go test -json -v $(go list -f '{{.Dir}}/...' -m) -coverprofile coverage-${{ matrix.os }}.out 2>&1 | tee /tmp/gotest.log | gotestfmt
         env:
           QODANA_LICENSE_ONLY_TOKEN: ${{ secrets.QODANA_LICENSE_ONLY_TOKEN }}
       - name: Run tests (with coverage) for Windows
